"""
Strategy Family Framework for Optimizer.

This module provides the base classes and dataclasses for trading strategies,
wrapping and extending the core strategy_family module for optimizer use.

Exports:
    - StrategySignal: Trading signal dataclass
    - StrategyFamily: Abstract base class for strategies

Note: This module provides alternative attribute names (direction/strength)
that are used by the optimizer module, while remaining compatible with the
core strategy_family implementation.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, ClassVar

import polars as pl


@dataclass(frozen=True, slots=True)
class StrategySignal:
    """
    Trading signal generated by a strategy.

    Attributes:
        timestamp: When the signal was generated
        symbol: Trading symbol (e.g., "AAPL", "SPY")
        direction: Direction signal (-1=short, 0=flat, +1=long)
        strength: Signal strength/confidence (0.0 to 1.0)
        metadata: Additional data (indicator values, reasoning, etc.)
    """

    timestamp: datetime
    symbol: str
    direction: int  # -1, 0, +1
    strength: float = 1.0
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate signal values after initialization."""
        if self.direction not in (-1, 0, 1):
            object.__setattr__(self, "direction", max(-1, min(1, self.direction)))
        if not 0.0 <= self.strength <= 1.0:
            object.__setattr__(self, "strength", max(0.0, min(1.0, self.strength)))


class StrategyFamily(ABC):
    """
    Abstract base class for trading strategy families.

    All strategy implementations must inherit from this class and implement
    the required abstract methods.

    Class Attributes:
        family_name: Name identifying the strategy family

    Example:
        >>> class MyStrategy(StrategyFamily):
        ...     family_name = "my_strategy"
        ...
        ...     def __init__(self, lookback: int = 20):
        ...         self._lookback = lookback
        ...
        ...     @classmethod
        ...     def get_default_params(cls) -> dict[str, Any]:
        ...         return {"lookback": 20}
        ...
        ...     def generate_signals(self, df: pl.DataFrame) -> list[StrategySignal]:
        ...         return []
    """

    family_name: ClassVar[str] = "base"

    @classmethod
    @abstractmethod
    def get_default_params(cls) -> dict[str, Any]:
        """
        Get default parameters for this strategy family.

        Returns:
            Dictionary of parameter names to default values.
        """
        ...

    @abstractmethod
    def generate_signals(self, decision_frame: pl.DataFrame) -> list[StrategySignal]:
        """
        Generate trading signals from a decision frame.

        Args:
            decision_frame: Polars DataFrame containing market data

        Returns:
            List of StrategySignal objects
        """
        ...

    def get_parameter_grid(self) -> dict[str, list[Any]]:
        """
        Get parameter grid for optimization.

        Returns:
            Dictionary mapping parameter names to lists of values.
        """
        return {}

    def validate_decision_frame(self, df: pl.DataFrame) -> bool:
        """
        Validate that decision frame has required columns.

        Args:
            df: Decision frame to validate

        Returns:
            True if frame has required columns

        Raises:
            ValueError: If required columns are missing
        """
        required_columns = {"timestamp", "symbol"}
        missing = required_columns - set(df.columns)
        if missing:
            raise ValueError(f"Decision frame missing required columns: {missing}")
        return True

    def __repr__(self) -> str:
        """String representation of strategy."""
        return f"{self.__class__.__name__}(family={self.family_name!r})"
