"""
Strategy Family Framework (T4.01).

Provides the base class and signal dataclass for all trading strategies
in the autonomous equities trading engine.

Key Components:
- StrategySignal: Dataclass representing a trading signal
- StrategyFamily: Abstract base class for strategy implementations

Design Principles:
- Strategies must be deterministic and reproducible
- Signals include confidence scores for position sizing
- Metadata captures indicator values for debugging/analysis
- Parameter grids enable systematic optimization
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import polars as pl


@dataclass(frozen=True, slots=True)
class StrategySignal:
    """
    Represents a trading signal generated by a strategy.

    Attributes:
        timestamp: When the signal was generated
        symbol: Trading symbol (e.g., "AAPL", "SPY")
        signal: Direction signal (-1=short, 0=flat, +1=long)
        confidence: Signal strength/confidence (0.0 to 1.0)
        metadata: Additional data (indicator values, reasoning, etc.)

    Examples:
        >>> signal = StrategySignal(
        ...     timestamp=datetime.now(timezone.utc),
        ...     symbol="AAPL",
        ...     signal=1,
        ...     confidence=0.85,
        ...     metadata={"source": "ma_crossover", "rsi": 65.5}
        ... )
        >>> signal.signal
        1
        >>> signal.confidence
        0.85
    """

    timestamp: datetime
    symbol: str
    signal: int  # -1, 0, +1
    confidence: float
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate signal values after initialization."""
        # Note: frozen=True means we can't modify, but post_init still runs
        # We rely on users to provide valid values
        # Validation happens at usage time in generate_signals
        pass


class StrategyFamily(ABC):
    """
    Abstract base class for trading strategy families.

    All strategy implementations must inherit from this class and implement:
    - name: Strategy family identifier
    - parameters: Current parameter configuration
    - generate_signals: Signal generation from decision frames
    - get_parameter_grid: Parameter combinations for optimization

    Design Goals:
    - Consistent interface for backtester integration
    - Support for parameter optimization
    - Reproducible signal generation
    - Clear separation of strategy logic

    Example Implementation:
        >>> class MyStrategy(StrategyFamily):
        ...     def __init__(self, lookback: int = 20):
        ...         self._lookback = lookback
        ...
        ...     @property
        ...     def name(self) -> str:
        ...         return "my_strategy"
        ...
        ...     @property
        ...     def parameters(self) -> dict[str, float | int | str]:
        ...         return {"lookback": self._lookback}
        ...
        ...     def generate_signals(self, df: pl.DataFrame) -> list[StrategySignal]:
        ...         # Implementation here
        ...         return []
        ...
        ...     def get_parameter_grid(self) -> dict[str, list[float | int]]:
        ...         return {"lookback": [10, 20, 50, 100]}
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """
        Strategy family name.

        Returns:
            Unique identifier for the strategy family (e.g., "trend", "mean_reversion")
        """
        ...

    @property
    @abstractmethod
    def parameters(self) -> dict[str, float | int | str]:
        """
        Current strategy parameters.

        Returns:
            Dictionary of parameter names to their current values
        """
        ...

    @abstractmethod
    def generate_signals(self, decision_frame: pl.DataFrame) -> list[StrategySignal]:
        """
        Generate trading signals from a decision frame.

        Args:
            decision_frame: Polars DataFrame containing:
                - timestamp: datetime column
                - symbol: str column
                - close: float (required for most strategies)
                - high, low, open: float (for range-based indicators)
                - volume: float (for volume-based indicators)
                - Additional columns as needed by specific strategies

        Returns:
            List of StrategySignal objects, one per decision point where
            the strategy has an opinion (may skip neutral periods)

        Notes:
            - Signals should be generated without look-ahead bias
            - Use only data available at each timestamp
            - Empty list is valid when strategy has no signal
        """
        ...

    @abstractmethod
    def get_parameter_grid(self) -> dict[str, list[float | int]]:
        """
        Get parameter grid for optimization.

        Returns:
            Dictionary mapping parameter names to lists of values to test.
            Used by parameter sweep to explore strategy configurations.

        Example:
            >>> strategy.get_parameter_grid()
            {
                "lookback": [10, 20, 50],
                "threshold": [0.5, 1.0, 2.0]
            }
        """
        ...

    def validate_decision_frame(self, df: pl.DataFrame) -> bool:
        """
        Validate that decision frame has required columns.

        Args:
            df: Decision frame to validate

        Returns:
            True if frame has required columns

        Raises:
            ValueError: If required columns are missing
        """
        required_columns = {"timestamp", "symbol", "close"}
        missing = required_columns - set(df.columns)
        if missing:
            raise ValueError(f"Decision frame missing required columns: {missing}")
        return True

    def __repr__(self) -> str:
        """String representation of strategy."""
        return f"{self.__class__.__name__}(name={self.name!r}, params={self.parameters})"
